---
service: aws-stelios-test

provider:
  name: aws
  region: eu-west-1
  stage: dev
  profile: cloudreach-lab
  runtime: python2.7
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListAllMyBuckets
      Resource:
        - "*"

functions:

  api:
    handler: wsgi.handler
    events:
      # - http: ANY {proxy+}
      - http:
          path: /stelios
          method: get
          integration: lambda-proxy

custom:
  wsgi:
    app: api.app

plugins:
  - serverless-wsgi